language: php

php: [5.5, 5.6, hhvm]

addons:
  postgresql: '9.3'
services:
  - mongodb

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - vendor

before_script:
  - echo 'extension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - psql -U postgres -c 'create database event_store;'
  - psql -U postgres < example/sql/event_store.sql
  - psql -U postgres -c 'create database event_store_projection;'
  - psql -U postgres < example/sql/event_store_projection.sql
  - composer install --prefer-dist

script:
  - ./bin/phpspec run -fpretty
  - ./bin/funk funk
